name: GiraOne MQTT Bridge
version: v0.0.1
slug: giraone_mqtt_bridge
description: Bridge betwween GiraOne Home Server and MQTT
url: https://github.com/home-assistant/apps-example/tree/main/example
arch:
  - amd64
services:
  - mqtt:need
stage: experimental
hassio_api: true
init: false
options:
  GIRA_SERVER: null
  GIRA_USER: null
  GIRA_PASSWORD: null
  MQTT_USE_INTERNAL_BROKER: true
  MQTT_BROKER: null
  MQTT_PORT: 1883
  MQTT_USER: null
  MQTT_PASSWORD: null
  LOG_LEVEL: info
schema:
  GIRA_SERVER: str
  GIRA_USER: str
  GIRA_PASSWORD: password
  MQTT_USE_INTERNAL_BROKER: bool
  MQTT_BROKER: str
  MQTT_PORT: int
  MQTT_USER: str
  MQTT_PASSWORD: password
  LOG_LEVEL: list(trace|debug|info|warning|error)
image: matgroe/hassio-giraone-mqtt-bridge
